In [1]:
import pandas as pd
import numpy as np

### Numpy

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [6]:
arr2d = np.array([[1,2,3], [2,3,4]])
arr2d

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
arr3d = np.array([
    [[1,2,3], [2,3,4], [4,5,6]],
    [[1,2,3], [2,3,4], [4,5,6]],
    [[1,2,3], [2,3,4], [4,5,6]]
])
arr3d

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [9]:
size = 5
fix = [0] * size
fix

[0, 0, 0, 0, 0]

In [11]:
random = np.full((2,2), 7)
random

array([[7, 7],
       [7, 7]])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
# Reshaping array

arr = np.array([1,2,3,4,5,6,7,8,9])

new_array = arr.reshape(3,3)
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr = np.array([[1,2,3], [2,3,4]])
arr.T

array([[1, 2],
       [2, 3],
       [3, 4]])